# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: mvn clean install -DskipTests -Drat.skip=true
- script: |
    cd flink-python
    mvn test
- script: |
    cd flink-python
    python setup.py sdist
    cd dist
    for /f %%i in ('dir /b') do (python -m pip install %%i)
    cd ../
    python -m pip install pytest
    python -m pip install "grpcio-tools>=1.3.5,<=1.14.2"
    pytest
#- task: Maven@3
#  inputs:
#    mavenPomFile: 'pom.xml' 
#    goals: 'clean install'
#    options: '-DskipTests'
#    javaHomeOption: 'JDKVersion' # Options: jDKVersion, path
#    jdkVersionOption: '1.8' # Optional. Options: default, 1.11, 1.10, 1.9, 1.8, 1.7, 1.6
