# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

pool:
  vmImage: 'windows-latest'

jobs:
- job:
  timeoutInMinutes: 120
  steps:
  - script: mvn clean install -DskipTests -Drat.skip=true
  - script: |
      cd flink-python
      mvn test
  - script: |
      cd flink-python
      python setup.py sdist
      cd dist
      for /f %%i in ('dir /b') do (python -m pip install %%i)
      cd ../
      python -m pip install pytest
      python -m pip install "grpcio-tools>=1.3.5,<=1.14.2"
      pytest
      conda create -n py36 python=3.6
      conda activate py36
      cd dist
      for /f %%i in ('dir /b') do (python -m pip install %%i)
      cd ../
      python -m pip install pytest
      python -m pip install "grpcio-tools>=1.3.5,<=1.14.2"
      pytest
      conda create -n py35 python=3.5
      conda activate py35
      cd dist
      for /f %%i in ('dir /b') do (python -m pip install %%i)
      cd ../
      python -m pip install pytest
      python -m pip install "grpcio-tools>=1.3.5,<=1.14.2"
      pytest
